Projects/pizza_project/pizzas/urls.py
"""Defines URL patterns for pizza_project."""

from django.urls import path

from . import views

app_name = 'pizzas'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page that shows all pizzas.
    path('pizzas/', views.pizzas, name='pizzas'),
    # Detail page for a single pizza.
    path('pizzas/<int:pizza_id>', views.pizza, name ='pizza'),
]

Projects/pizza_project/pizzeria_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls') )
]

Projects/pizza_project/pizzas/models.py
from django.db import models

# Create your models here.
class Pizza(models.Model):
    """Select a Pizza"""

    name = models.CharField(max_length=50)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model Pizza."""
        return self.name


class Topping(models.Model):
    """Select a Topping for the Pizza"""

    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "toppings"

    def __str__(self):
        """Return a string representation of the model Topping."""
        return self.name

Projects/pizza_project/pizzas/views.py
from django.shortcuts import render

# Create your views here.
from .models import Pizza

# Create your views here.
def index(request):
    """The home page for Pizzas."""
    return render(request, 'pizzas/index.html')

def pizzas(request):
    """Show all pizzas."""
    pizzas = Pizza.objects.order_by('date_added')
    context = {'pizzas': pizzas}
    return render(request, 'pizzas/pizzas.html', context)

def pizza(request, pizza_id):
    """Show a single pizza and all its toppings."""
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.order_by('-date_added')
    context = {'pizza': pizza, 'toppings': toppings}
    return render(request, 'pizzas/pizza.html', context)

Projects/pizza_project/pizzas/templates/pizzas/base.html
<p>
    <a href="{% url 'pizzas:index' %}">Info</a> -
    <a href="{% url 'pizzas:pizzas' %}">Pizzas</a>
</p>

{% block content %}{% endblock content %}

Projects/pizza_project/pizzas/templates/pizzas/index.html
{% extends 'pizzas/base.html' %}

<p>Create your favourite pizza and make the order straight from our site!!! :)</p>

Projects/pizza_project/pizzas/templates/pizzas/pizza.html
{% extends 'pizzas/base.html' %}

{% block content %}

    <p>Pizza: {{ pizza.name }}</p>

    <p>Toppings:</p>
    <ul>
        {% for topping in toppings %}
            <li>
                <p>{{ topping.date_added|date:'M d, Y H:i' }}</p>
                <p>{{ topping.name|linebreaks }}</p>
            </li>
        {% empty %}
            <li>There are no entries for this pizza yet.</li>
        {% endfor %}
    </ul>

{% endblock content %}

Projects/pizza_project/pizzas/templates/pizzas/pizzas.html
{% extends 'pizzas/base.html' %}

{% block content %}

    <p>Pizzas</p>
    <ul>
        {% for pizza in pizzas %}
            <li>
                <a href="{% url 'pizzas:pizza' pizza.id %}">
                    {{ pizza.name }}</a>
            </li>
        {% empty %}
            <li>No pizza has been added yet.</li>
        {% endfor %}
    </ul>

{% endblock content %}