Projects/blog/accounts/urls.py
"""Defines URL patterns for accounts."""

from django.urls import path, include

from . import views

app_name = 'accounts'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
]

Projects/blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('blogs.urls')),

]

Projects/blog/blogs/urls.py
"""Defines URL patterns for blogs."""

from django.urls import path

from . import views

app_name = 'blogs'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page that shows all posts.
    path('blogs/', views.blogs, name='blogs'),
    # Detail page for a single blog.
    path('blogs/<int:blog_id>', views.blog, name='blog'),
    # Page for adding a new blog.
    path('new_blog/', views.new_blog, name='new_blog'),
    # Page for adding a new entry.
    path('new_post/<int:blog_id>/', views.new_post, name='new_post'),
    # Page for editing an entry.
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
]

Projects/blog/accounts/models.py
from django.db import models

# Create your models here.

Projects/blog/blogs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Blog(models.Model):
    """A blog """

    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation of the model."""
        return self.text


class Post(models.Model):
    """Information about a blog."""

    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "posts"

    def __str__(self):
        """Return a simple string representing the post."""
        # Add ellipsis (...) >= 50 characters
        if len(self.text) >= 50:
            return f"{self.text[:50]}..."
        else:
            return self.text

Projects/blog/blogs/forms.py
from django import forms

from .models import Blog, Post

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['text']
        labels = {'text': ''}

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

Projects/blog/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in an then redirect to home page.
            login(request, new_user)
            return redirect('blogs:index')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

Projects/blog/blogs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Blog, Post
from .forms import BlogForm, PostForm

# Create your views here.
def index(request):
    """The home page for Learning Log."""
    return render(request, 'blogs/index.html')

@login_required
def blogs(request):
    """Show all posts."""
    blogs = Blog.objects.filter(owner=request.user).order_by('date_added')
    context = {'blogs': blogs}
    return render(request, 'blogs/blogs.html', context)

@login_required
def blog(request, blog_id):
    """Show a single blog and all its posts."""
    blog = Blog.objects.get(id=blog_id)
    # Make sure the blog belongs to the current user.
    check_blog_owner(request, blog)
    posts = blog.post_set.order_by('-date_added')
    context = {'blog': blog, 'posts': posts}
    return render(request, 'blogs/blog.html', context)

@login_required
def new_blog(request):
    """Add a new blog."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = BlogForm()
    else:
        # POST data submitted; process data.
        form = BlogForm(data=request.POST)
        if form.is_valid():
            new_blog = form.save(commit=False)
            new_blog.owner = request.user
            new_blog.save()
            return redirect('blogs:blogs')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'blogs/new_blog.html', context)

@login_required
def new_post(request, blog_id):
    """Add a new post for a particular blog."""
    blog = Blog.objects.get(id=blog_id)

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = PostForm()
    else:
        # POST data submitted; process data.
        form = PostForm(data=request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.blog = blog
            # Make sure the blog belongs to the current user.
            check_blog_owner(request, blog)
            new_post.save()
            return redirect('blogs:blog', blog_id=blog_id)

    # Display a blank or invalid form.
    context = {'blog': blog, 'form': form}
    return render(request, 'blogs/new_post.html', context)
    
@login_required
def edit_post(request, post_id):
    """Edit an existing post."""
    post = Post.objects.get(id=post_id)
    blog = post.blog
    # Make sure the blog belongs to the current user.
    check_blog_owner(request, blog)
    if request.method != 'POST':
        # Initial request; pre-fill form with the current post.
        form = PostForm(instance=post)
    else:
        # POST data submitted; process data.
        form = PostForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:blog', blog_id=blog.id)

    context = {'post': post, 'blog': blog, 'form': form}
    return render(request, 'blogs/edit_post.html', context)

def check_blog_owner(request, blog):
    if blog.owner != request.user:
        raise Http404

Projects/blog/blogs/templates/blogs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blogs</title>

    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'blogs:index' %}">
                Blogs</a>
        
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blogs:blogs' %}">
                            Blogs</a></li>
                </ul>   <!-- End of links on left side of navbar -->

                <!-- Account-related links -->
                <ul class="navbar-nav ms-auto mb-2 mb-md-0">

                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text me-2">Hello, {{ user.username }}.
                        </span></li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:register' %}">
                            Register</a></li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}">
                            Log in</a></li>
                    {% endif %}
        
                </ul> <!-- End of account-related links -->

                {% if user.is_authenticated %}
                <form action="{% url 'accounts:logout' %}" method='post'>
                  {% csrf_token %}
                  <button name='submit' class='btn btn-outline-secondary btn-sm'>
                    Log out</button>
                </form>
              {% endif %}

            </div> <!-- Closes collapsible parts of navbar -->
        </div> <!-- Closes navbar's container -->
    </nav> <!-- End of navbar -->


    <main class="container">
        <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
        </div>

        <div>
        {% block content %}{% endblock content %}
        </div>
    </main>

</body>
</html>

Projects/blog/blogs/templates/blogs/blog.html
{% extends 'blogs/base.html' %}

{% block page_header %}
    <h1>{{ topic.text }}</h1>
{% endblock page_header %}

{% block content %}
    <p>
        <a href="{% url 'blogs:new_post' blog.id %}">Add new post</a>
    </p>
    {% for post in posts %}
        <div class="card mb-3">
            <!-- Card header with timestamp and edit link -->
             <h4 class="card-header">
                {{ post.date_added|date:'M d, Y H:i' }}
                <small><a href="{% url 'blogs:edit_post' post.id %}">edit entry</a></small>
             </h4>
            <!-- Card body with entry text -->
             <div class="card-body">{{ post.text|linebreaks }}</div>
        {% empty %}
            <p>There are no posts for this blog yet.</p>
        {% endfor %}

{% endblock content %}

Projects/blog/blogs/templates/blogs/blogs.html
{% extends 'blogs/base.html' %}

{% block page_header %}
    <h1>Blogs</h1>
{% endblock page_header %}

{% block content %}

    <ul class="list-group border-bottom pb-2 mb-4">
        {% for blog in blogs %}
            <li class="list-group-item border-0">
                <a href="{% url 'blogs:blog' blog.id %}">
                    {{ blog.text }}</a>
            </li>
        {% empty %}
            <li class="list-group-item border-0">No blogs have been added yet.</li>
        {% endfor %}
    </ul>

    <a href="{% url 'blogs:new_blog' %}">Add a new blog</a>

{% endblock content %}

Projects/blog/blogs/templates/blogs/edit_post.html
{% extends 'blogs/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
    <h1>Edit this post:</h1>
{% endblock page_header %}

{% block content %}

    <p><a href="{% url 'blogs:blog' blog.id %}">{{ topic }}</a></p>

    <p>Edit entry:</p>

    <form action="{% url 'blogs:edit_post' post.id %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="Save changes" %}
    </form>

{% endblock content %}

Projects/blog/blogs/templates/blogs/index.html
{% extends 'blogs/base.html' %}

{% block page_header %}
    <div class="p-3 mb-4 bg-light border rounded-3">
        <div class="container-fluid py-4">
            <h1 class="display-3">Welcome to the homepage!</h1>

            <p class="lead">Blogs with individual posts for you to take a look through.</p>
            <a class="btn btn-primary btn-lg mt-1" href="{ % url 'accounts:register' %}">Register &raquo;</a>
        </div>
    </div>
{% endblock page_header %}

Projects/blog/blogs/templates/blogs/new_blog.html
{% extends 'blogs/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
    <h2>Add a new blog:</h2>
{% endblock page_header %}

{% block content %}
    <p>Add a new blog:</p>

    <form action="{% url 'blogs:new_blog' %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="Add blog" %}
    </form>

{% endblock content %}

Projects/blog/blogs/templates/blogs/new_post.html
{% extends 'blogs/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
    <h2>Add a new post:</h2>
{% endblock page_header %}

{% block content %}
    <p><a href="{% url 'blogs:blog' blog.id %}">{{ blog }}</a></p>

    <p>Add a new entry:</p>
    <form action="{% url 'blogs:new_post' blog.id %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="Add post" %}
    </form>

{% endblock content %}